### PR TITLE
WMS ID: 11116 - "How to IGNITE your Oracle Tenancy" 

### PR DESCRIPTION
**Pull request by csmanea**
Self QA completed.

Created a new LiveLabs workshop

### CODE REVIEW

**Comment by anooshapilli** [comment]
@csmanea For the need-help lab, you can use object storage links to the need-help labs in your manifest.json instead of copying the lab files. Use the below links:

For LiveLabs version: https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/need-help/need-help-livelabs.md

For the free tier version: https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/need-help/need-help-freetier

Similarly, update the get started lab links in manifest.json with the object storage links instead of the path
free tier - https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/cloud-login/pre-register-free-tier-account.md

livelabs - https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/cloud-login/cloud-login.md

**Comment by anooshapilli** [comment]
As this is a new workshop, please submit the filled out [Self QA document](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) to [livelabs-help-oci_us@oracle.com](mailto:livelabs-help-oci_us@oracle.com) mailbox for review. If everything looks good the stakeholder will confirm to approve the PR and then we will move the workshop to production.

**Comment by klazarz** [comment]
@csmanea can you please remove the .vscode directory from your commit?

**Comment by klazarz** [comment]
@csmanea also please make sure that all images contain alternate text ["Alternate etxt](pathtoimage)
Furthermore, image files must not contain '_' - only '-' is allowed

**Comment by klazarz** [comment]
@csmanea i will close this PR for now as we are doing some bigger cleanup - we can chat next week

**Pull request closed without merging**
